### ISSUE TITLE
primo-explore-dom and VE?

### ISSUE THREAD

**Issue by jhercher** [mehmetc/primo-explore-dom#4]
We're currently looking into a switch to Primo VE and would be interested if this library will work with VE?
It might not be dependent, but I wan't to make sure that there no caveats in using primo-explore-dom with VE…
Thank you, 
Johannes

**Comment by mehmetc** [comment]
NO, that is the simple answer. 
Longer answer ... Looking up fines and loans will not work because Alma has different end points for that all the rest should work. But I'm working on a newer version. See the [project](https://github.com/mehmetc/41SLSP_NETWORK/tree/master/src/primo) I did for RZS but it is not a npm by it self.
